customhost = "employee01.cloyqya4qspy.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee01"
custombucket = "aws-01project"
customregion = "ap-south-1"
